
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
cache: cargo
deploy:
  provider: bintray
  file: "Path to a descriptor file, containing information for the Bintray upload"
  user: "jonaylor89"
  key: "Bintray API key"
  skip_cleanup: true # to upload artifacts created during the build